
platform :ios, '10.0'

target 'CGFrameworkExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking','~> 3.0.0' 
  #pod 'ReactiveObjC','3.1.1'

  #pod 'JCore', '2.1.4-noidfa'
  #pod 'JPush', '3.2.4-noidfa'

  # Pods for CGFrameworkExample

end
